//
// Generated file, do not edit! Created by nedtool 5.6 from UpdatePacket.msg.
//

#ifndef __UPDATEPACKET_M_H
#define __UPDATEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>UpdatePacket.msg:1</tt> by nedtool.
 * <pre>
 * packet UpdatePacket
 * {
 *     string source;
 *     string destination;
 *     double cost;
 * }
 * </pre>
 */
class UpdatePacket : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string source;
    ::omnetpp::opp_string destination;
    double cost;

  private:
    void copy(const UpdatePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdatePacket&);

  public:
    UpdatePacket(const char *name=nullptr, short kind=0);
    UpdatePacket(const UpdatePacket& other);
    virtual ~UpdatePacket();
    UpdatePacket& operator=(const UpdatePacket& other);
    virtual UpdatePacket *dup() const override {return new UpdatePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
    virtual double getCost() const;
    virtual void setCost(double cost);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdatePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdatePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEPACKET_M_H

